Repository eslint-community/eslint-plugin-promise, pull requests merged in 2024-07, with the labels that each got.

#441 chore: add `format` workflow
  .github/workflows/format.yml
  package.json
Labels: chore

#486 feat: add `name` property to configs (for use with tooling)
  index.js
Labels: enhancement

#490 fix: remove `name` from eslintrc config; fixes #489
  index.js
Labels: bug :bug:

#491 docs: add for `prefer-await-to-callbacks`; fixes #118
  README.md
  docs/rules/prefer-await-to-callbacks.md
  rules/prefer-await-to-callbacks.js
Labels: documentation :book:

#493 fix(`always-return`): treat process.exit() or process.abort() as an acceptable "return"
  __tests__/always-return.js
  rules/always-return.js
Labels: bug :bug:

#492 docs: recommend `util.promisify` instead of pify
  README.md
  docs/rules/avoid-new.md
  docs/rules/no-callback-in-promise.md
  rules/avoid-new.js
  rules/no-callback-in-promise.js
Labels: documentation :book:

#484 chore!: Update node versions to align with eslint v9
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: chore

#483 chore: bump dev dependencies
  .eslintrc.json
  .husky/pre-commit
  README.md
  __tests__/index.js
  package-lock.json
  package.json
  rules/always-return.js
  rules/no-multiple-resolved.js
  rules/no-nesting.js
  rules/no-new-statics.js
  rules/param-names.js
Labels: chore

#495 feat(`catch-or-return`, `prefer-await-to-then`): do not report Cypress commands
  __tests__/catch-or-return.js
  __tests__/prefer-await-to-then.js
  rules/catch-or-return.js
  rules/lib/is-member-call-with-object-name
  rules/prefer-await-to-then.js
Labels: enhancement

#502 feat: new rule `spec-only` to check for non-spec Promise methods
  README.md
  __tests__/no-new-statics.js
  __tests__/spec-only.js
  docs/rules/spec-only.md
  index.js
  rules/lib/is-promise.js
  rules/lib/promise-statics.js
  rules/spec-only.js
Labels: enhancement

#496 feat(`prefer-await-to-then`): ignore constructor scope unless with `strict` option
  __tests__/prefer-await-to-then.js
  rules/lib/is-inside-callback.js
  rules/prefer-await-to-then.js
Labels: enhancement
